// <auto-generated />
using DAL.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DAL.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("City")
                        .IsRequired();

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Chapra",
                            Email = "pkrahul.ks16@gmail.com",
                            Name = "Mary"
                        },
                        new
                        {
                            Id = 2,
                            City = "Patna",
                            Email = "rahull.ks16@gmail.com",
                            Name = "Darry"
                        });
                });

            modelBuilder.Entity("DAL.Models.Teacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("About")
                        .IsRequired();

                    b.Property<string>("City")
                        .IsRequired();

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<int>("Gender");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("Skills");

                    b.HasKey("Id");

                    b.ToTable("Teachers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            About = "I can teach from class 5 to 10 , All Subjects.",
                            City = "Patna",
                            Email = "rahulll.ks18@gmail.com",
                            Gender = 0,
                            Name = "David",
                            Skills = "MATH, ENGLISH,SCIENCE"
                        },
                        new
                        {
                            Id = 2,
                            About = "I can teach from class 8 to 10 , All Subjects.",
                            City = "Chapra",
                            Email = "pchristy@gmail.com",
                            Gender = 1,
                            Name = "Christy Pearly",
                            Skills = "MATH, ENGLISH,SCIENCE"
                        });
                });

            modelBuilder.Entity("DAL.Models.Tution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("City")
                        .IsRequired();

                    b.Property<string>("CreaterId")
                        .IsRequired();

                    b.Property<string>("Description")
                        .IsRequired();

                    b.Property<bool>("Status");

                    b.HasKey("Id");

                    b.ToTable("Tutions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "chapra",
                            CreaterId = "rahull.ks16@gmail.com",
                            Description = "I can teach from class 5 to 10 , All Subjects.",
                            Status = true
                        },
                        new
                        {
                            Id = 2,
                            City = "Patna",
                            CreaterId = "pkrahul.ks16@gmail.com",
                            Description = "I can teach from class 5 to 10 , All Subjects.",
                            Status = true
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
